service: nr-students-edition

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function

custom:
  defaultStage: dev
  defaultRegion: us-east-2
  environment: ${file(.env):${self:provider.stage}, file(.env):default}


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${env:STAGE, self:custom.defaultStage}
  region: ${env:REGION, self:custom.defaultRegion}
  environment:
    TEST: ${env:TEST, 'default_value'}

functions:
  ping:
    handler: src/functions/ping.ping
    memorySize: 512
    events:
      - http:
          path: /ping
          method: get
          cors: true
