service: nr-students-edition

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function

useDotenv: true

custom:
  defaultStage: dev
  defaultRegion: us-east-2
  environment: ${file(.env):${self:provider.stage}, file(.env):default}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${env:STAGE, self:custom.defaultStage}
  region: ${env:REGION, self:custom.defaultRegion}
  environment:
    TEST: ${env:TEST, 'default_value'}

functions:
  save-data:
    handler: src/functions/save.save
    description: Saves students data to the database
    memorySize: 512
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /students
          method: post
          cors: true
  auth-github:
    handler: src/functions/auth.authGithub
    description: Authenticates via GitHub service
    memorySize: 512
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /github/auth
          method: get
          cors: true
  user-data-github:
    handler: src/functions/get-user-data.getUserData
    description: Gets user data from the github api, checks if user is a student
    memorySize: 512
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /github/users
          method: get
          cors: true
  check-validation-status:
    handler: src/functions/check-validation-status.check
    description: Checks validation status based on given account id
    memorySize: 512
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /check
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                accountId: true
